server:
  port: 8090
  servlet:
    context-path: /dna/sample

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://34.64.197.81:5432/portal
#    url: jdbc:postgresql://34.64.86.103:5432/postgres
    username: vtw
    password: vtw123#
  jpa:
    open-in-view: false

# Apache Camel
camel:
  springboot:
    main-run-controller: true
    stream-caching-enabled: false
    jmx-enabled: false
    dev-console-enabled: true
    routes-include-pattern: file:src/main/resources/yaml/sample.yaml
    tracing: true
    tracing-standby: true
    backlog-tracing: true

