server:
  port: 8090
  servlet:
    context-path: /dna/sample

spring:
#  DB 연결정보
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://34.64.197.81:5432/portal
    username: vtw
    password: vtw123#
  hikari:
    maximum-pool-size: 20

  jpa:
    open-in-view: false

# Apache Camel
camel:
  springboot:
    main-run-controller: true
    stream-caching-enabled: false
    jmx-enabled: false
    dev-console-enabled: true
#    route를 생성하기위해 읽어들이는 파일
    routes-include-pattern: file:src/main/resources/yaml/sample.yaml
    tracing: true
    tracing-standby: true
    backlog-tracing: true

